### ISSUE TITLE
Figure out how to update test-db when new columns or tables are added

### ISSUE THREAD

**Issue by vaahtokarkki** [UniversityOfHelsinkiCS/sis-importer#146]
Currently tests fail when new columns or tables are added as tests tries to selected columns which does not exists in the db

**Comment by valtterikantanen** [comment]
A new version of sis-importer-db will now be pushed to Toska's registry if new migrations have been added

https://github.com/UniversityOfHelsinkiCS/sis-importer/blob/c3c34136bae2291232cadda7e04d885634852f19/.github/workflows/importer-mankeli-staging.yaml#L12-L36
