### ISSUE TITLE
create api for university structure

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/sis-importer#57]
which study programme belongs to which faculty and so on and forth
(ask @xneme for details)

npm install hys (helsingin yliopiston struktuuri)

**Comment by woltsu** [comment]
what in tarnation

**Comment by Jakousa** [comment]
api

**Comment by Veikkosuhonen** [comment]
We made [jami](https://github.com/UniversityOfHelsinkiCS/jami) and that does the thing
